# This is a basic workflow to help you get started with Actions

name: CII

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: 0/5 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: PDF To Markdown workflow
        # You may pin to the exact commit or the version.
        # uses: northy/pdf-to-markdown-workflow@397f8e6dbe0ae2bf5c1b784202a038dccd67eefa
        uses: northy/pdf-to-markdown-workflow@v1.0
        with:
          # Input PDF file
          pdf_input: LordHarsh/certificates/Coursera Course- Convolutional Neural Networks.pdf # optional, default is source.pdf
          # Output pngs folder
          # Source markdown file
          source_md: LordHarsh/README.md # optional, default is source.md
